### ISSUE TITLE
How ag-grid is associated with an angular formControlName (angular)

### ISSUE THREAD

**Issue by smile2014** [ag-grid/ag-grid-angular#192]
##
    <div [formGroup]="form">
    <input   [formControlName]="question.key"/>
    <ag-grid-angular style="width: 500px; height: 115px;"
                 [formControlName]="question.items"
                 class="ag-fresh"
                 [rowData]="rowData"
                 [columnDefs]="columnDefs"
                 [gridOptions]="gridOptions"
                 (gridReady)="onGridReady($event)">
    </ag-grid-angular>
    </div>
###

**Comment by seanlandsman** [comment]
I'm afraid I'm not sure what you're raising here. 

If you can expand on the issue please feel free to raise a new issue here: https://github.com/ag-grid/ag-grid

**Comment by colingaj** [comment]
It seems to me that the only way you can associate formControlName with an ag-grid column is by defining the column as a new component and sticking that in the component's template. Is that correct? There is no way to define that as part of the columnDefs?

**Comment by seanlandsman** [comment]
If you want to use ag-Grid within an Angular form I suggest you try the guide here: https://medium.com/ag-grid/using-angular-forms-with-ag-grid-1efe00265535

**Comment by colingaj** [comment]
Hi, thanks for feedback. After writing my question I posted the same to StackOverflow here: 

https://stackoverflow.com/questions/56889160/using-formcontrolname-with-ag-grid-for-editable-columns

since I thought it would be more appropriate there. So basically, I am familiar with that link.... I guess you are saying that is the recommended way - i.e. we have to create cellRenderers for reactive forms to work. Maybe you can answer the StackOverflow question so others will see as well...

Thanks
